name: cladeaid
channels:
  - bioconda
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - biopython=1.85
  - htslib=1.22.1
  - mash=2.3
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - numpy=2.3.2
  - pandas=2.3.1
  - parallel=20250622
  - pysam=0.23.3
  - python=3.13.5
  - samtools=1.22.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - statsmodels=0.14.5
  - tqdm=4.67.1